--Part 1: Build and Explore the Table
CREATE TABLE ZOO_ANIMALS (
ID INTEGER PRIMARY KEY,
NAME TEXT NOT NULL,
SPECIES TEXT NOT NULL,
AGE INTEGER NOT NULL,
WEIGHT REAL NOT NULL
);

INSERT INTO ZOO_ANIMALS VALUES (1, 'Lion', 'Big Cat', 5, 190.0);
INSERT INTO ZOO_ANIMALS VALUES (2, 'Tiger', 'Big Cat', 3, 220.0);
INSERT INTO ZOO_ANIMALS VALUES (3, 'Elephant', 'Pachyderm', 12, 4500.0);
INSERT INTO ZOO_ANIMALS VALUES (4, 'Giraffe', 'Ungulate', 7, 800.0);
INSERT INTO ZOO_ANIMALS VALUES (5, 'Penguin', 'Bird', 2, 5.0);
INSERT INTO ZOO_ANIMALS VALUES (6, 'Panda', 'Bear', 6, 95.0);
INSERT INTO ZOO_ANIMALS VALUES (7, 'Cheetah', 'Big Cat', 4, 55.0);
INSERT INTO ZOO_ANIMALS VALUES (8, 'Rhino', 'Pachyderm', 9, 2300.0);

--Part 2: Select Distinct
--All species values including duplicates
SELECT SPECIES FROM ZOO_ANIMALS;
--Only unique species
SELECT DISTINCT SPECIES FROM ZOO_ANIMALS;

--Part 3: Count
--Total number of animals
SELECT COUNT(DISTINCT SPECIES) AS UNIQUE_SPECIES FROM ZOO_ANIMALS;
--Animals older than 5 years
SELECT COUNT(ID) AS TOTAL_ANIMALS FROM ZOO_ANIMALS;
--Count how many unique species
SELECT COUNT(ID) AS OLDER_THAN_5 FROM ZOO_ANIMALS WHERE AGE > 5;

--Part 4: SUM and AVG
--Total Weight of all animals
SELECT SUM(WEIGHT) AS TOTAL_WEIGHT FROM ZOO_ANIMALS;
--Average age of all animals
SELECT AVS(AGE) AS AVG_AGE FROM ZOO_ANIMALS;

SELECT
COUNT(ID) AS TOTAL_ANIMALS,
COUNT(DISTINCT SPECIES) AS UNIQUE_SPECIES,
SUM(WEIGHT) AS TOTAL_WEIGHT,
AVG(AGE) AS AVG_AGE
FROM ZOO_ANIMALS;